### ISSUE TITLE
Implement assigned -> unassigned functionality

### ISSUE THREAD

**Issue by karkar** [uwscope/scope-web#282] opened 2022-04-07 22:17 UTC
**Problem**
Registry: once an assessment/inventory/safety plan is assigned, it cannot be unassigned and will persist on patient side till they complete it. 

**Describe Desired Solution**
Once assigned, the clicking the same button again should unassign the item. 

**Describe Alternatives**

**Additional Context**

**Comment by jayfo** [comment] 2022-08-16 17:07
Duplicate of #336, closed in favor of greater detail there.

**Closed by jayfo** 2022-08-16 17:07 UTC
Labels: Registry client, Medium priority
